<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1848;CA1873</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LaneReady.Application\LaneReady.Application.csproj" />
    <ProjectReference Include="..\LaneReady.Infrastructure\LaneReady.Infrastructure.csproj" />
    <ProjectReference Include="..\LaneReady.RulesEngine\LaneReady.RulesEngine.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Web" />
    <PackageReference Include="Microsoft.Identity.Web.UI" />
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" />
    <PackageReference Include="Stripe.net" />
  </ItemGroup>
</Project>
